export const ACTION_TYPES = {
    TOGGLE_CART : 'TOGGLE_CART',
    LOAD_CART_ITEMS : 'LOAD_CART_ITEMS',
    ADD_TO_CART : 'ADD_TO_CART',
    LOAD_CART_QUANTITIES : 'LOAD_CART_QUANTITIES',
    DECREASE_QUANTITY : 'DECREASE_QUANTITY',
    REMOVE_ITEM : 'REMOVE_ITEM',
    TOTAL_PRICE : 'TOTAL_PRICE'
}